# Generated by Django 3.1.6 on 2021-02-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlpool', '0005_auto_20210212_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.TimeField(default=0)),
                ('input_data', models.CharField(max_length=4000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mlpool.mlmodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mlpool.task')),
            ],
        ),
    ]
