# Generated by Django 3.1.6 on 2021-02-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlpool', '0008_remove_result_spent_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('expert_target', models.CharField(max_length=4000)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mlpool.result')),
            ],
        ),
    ]
