# Generated by Django 3.1.6 on 2021-02-15 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlpool', '0010_mlmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='result',
            name='time_spent',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
